@startuml Class Diagram

interface IExplorerRaid {
    initialize(context : String): void
    takeDecision(): String
    acknowledgeResults(results : String): void
    deliverFinalReport(): void
}

package Actions {
    class Action
    enum ActionType
    Action --> ActionType
}
Action --> Directions

package Directions {
    enum CardinalDirection
    enum Orientation
    enum RelativeDirection
}

package Phases {
    interface Phase {
        getNextDecision(): Action
        getNextPhase(): Phase
        react(response : Response): void
        reachedEnd(): boolean
        isFinal(): boolean
        getCreeks(): AllPOIS
    }
    class FindCorner implements Phase
    class FindIsland implements Phase
    class ResetLeft implements Phase
    class ResetRight implements Phase
    class ScanLine implements Phase
    class TravelToIsland implements Phase
    class UTurn implements Phase
}


package Responses {
    interface Response {
        getCost(): int
        getStatus(): String
        getType(): ActionType
        getData(): Map<String, Value>
    }
    class NormalResponse implements Response
    class EchoResponse implements Response
    class ScanResponse implements Response
}

package POIs {
    class AllPOIS
    class ClosestCreek
    class POI
    enum POIType
    
    POI --> POIType
    ClosestCreek o-- AllPOIS
    AllPOIS *-- POI
}
POI *-- Coordinate

interface Scan {
    decide(): Action
    react(responseObj : JSONObject): void
    generateReport(): String
}
class Interlaced implements Scan

class Drone
class Coordinate
class Explorer
class Runner
enum ScanStatus
class Value

hide empty members

class Explorer implements IExplorerRaid

Runner --> Explorer

Explorer *-- Scan

Scan --> Action

Interlaced *-- Phase
Interlaced *-- Drone
Interlaced *-- ClosestCreek
Interlaced *-- Response
Interlaced --> Action

Drone --> Directions
Drone --> ScanStatus
Drone *-- Coordinate
Drone --> Action

Phase o-- Drone
Phase o-- AllPOIS
Phase --> Value
Phase --> Action

Response --> Value
Response --> Action

ScanLine *-- POI

@enduml